#!/bin/bash

# shellcheck disable=SC1091
[ -e /usr/local/lib/nubis/nubis-lib.sh ] && . /usr/local/lib/nubis/nubis-lib.sh || exit 1

consul_interface="eth1"

# wait for mac address to be ready once
# eni gets attached, we assume eni gets attached
attempts=0
until [ ! -z "${mac_eth}" ] || [ "${attempts}" -eq 10 ]; do
    log "Waiting on mac address of eth1 to be ready"
    mac_eth=$(__get_mac "${consul_interface}")
    sleep 5
    attempts=$((attempts +1))
done

# TODO: To make life easier we should use facter, of course that means we
# we have facter installed
ip_addr=$(curl --retry 5 -s -fq "http://169.254.169.254/latest/meta-data/network/interfaces/macs/${mac_eth}/local-ipv4s")

cat <<EOF | tee /etc/consul/interface.json
{
  "advertise_addr": "$ip_addr",
  "bind_addr": "$ip_addr"
}
EOF

find /etc/consul -type f -name '*.json' -print0 | xargs -0 --verbose sed -i -e "s/%%INTERFACE%%/${ip_addr}/g"
