#!/bin/bash

# Nubis library, installed via nubis-base
[ -e /usr/local/lib/nubis/nubis-lib.sh ] && . /usr/local/lib/nubis/nubis-lib.sh || exit 1

function __my_az() {
    local az=$1
    local region=$(get_region)
    local availability_zone=($(aws --region "${region}" ec2 describe-availability-zones --query "AvailabilityZones[0:3].ZoneName" --output text))
    if [[ ${availability_zone[0]} == ${az} ]]; then
        echo "Az1"
    elif [[ ${availability_zone[1]} == ${az} ]]; then
        echo "Az2"
    else
        echo "Az3"
    fi
}

function __get_eip_id() {
    if [ -z "$1" ]; then echo "Usage: $FUNCNAME [availablity zone]"; return 1; fi
    local az=$1
    local my_az=$(__my_az ${az})
    local region=$(get_region)

    eip_id=$(aws --region "${region}" cloudformation describe-stacks --stack-name "${NUBIS_STACK}" --query "Stacks[].Outputs[?OutputKey=='Eip${my_az}'].OutputValue" --output text)
    echo "${eip_id}"
}

# Meat and potatoes of script

AVAILABILITY_ZONE=$(get_availaibility_zone)
ENI_ID=$(get_eni_id eth0)
EC2_REGION=$(get_region)
INSTANCE_ID=$(get_instance_id)

echo -n "Waiting for instance to come up ... "
aws ec2 wait instance-running --instance-ids ${INSTANCE_ID} --region ${EC2_REGION}
echo "Done"

# First, check with CloudFormation to see if we can find our IP
attempts=0
until [ ! -z "${ELASTICIP_ID}" ] || [ "${attempts}" -eq 10 ]; do
    log "Waiting on Elastic IP to be ready"
    ELASTICIP_ID=$(__get_eip_id ${AVAILABILITY_ZONE})
    sleep 5
    let attempts++
done

if [[ -z "${INSTANCE_ID}" ]]; then
    log "ERROR: Instance ID not found"
    exit 1
fi

aws ec2 associate-address --network-interface-id ${ENI_ID} --allocation-id ${ELASTICIP_ID} --region ${EC2_REGION}
RV=$?

if [[ ${RV} != 0 ]]; then
    log "ERROR: Unable to associate elastic IP ${ELASTICIP_ID} to instance ${INSTANCE_ID} (${ENI_ID})"
    exit ${RV}
else
    # We assume that if return value is not 0 then we have successfully associated an EIP
    log "SUCCESS: Associated ${ELASTICIP_ID} to instance ${INSTANCE_ID} (${ENI_ID})"
fi
