#!/bin/bash

[ -e /usr/local/lib/nubis/nubis-lib.sh ] && . /usr/local/lib/nubis/nubis-lib.sh || exit 1

mac_eth1=$(__get_mac eth1)
ip_addr=$(curl -s -fq "http://169.254.169.254/latest/meta-data/network/interfaces/macs/${mac_eth1}/local-ipv4s")
vpc_cidr="http://169.254.169.254/latest/meta-data/network/interfaces/macs/${mac_eth1}/vpc-ipv4-cidr-block"

cat <<EOF | tee /etc/consul/interface.json
{
  "advertise_addr": "$ip_addr"
}
EOF

find /etc/confd/templates -type f -name '*.tmpl' | xargs --verbose sed -i -e "s/%%VPC_CIDR%%/$vpc_cidr/g"
