#!/bin/bash

# Nubis library, installed via nubis-base
# shellcheck disable=SC1091
[ -e /usr/local/lib/nubis/nubis-lib.sh ] && . /usr/local/lib/nubis/nubis-lib.sh || exit 1

AWS_DEFAULT_REGION=$(get_region)
export AWS_DEFAULT_REGION

# Meat and potatoes of script

ENI_ID=$(get_eni_id eth0)
INSTANCE_ID=$(get_instance_id)

# check our metadata
ELASTICIP_ID=$(nubis-metadata NUBIS_NAT_EIP)

if [[ -z "${INSTANCE_ID}" ]]; then
    log "ERROR: Instance ID not found"
    exit 1
fi

aws ec2 associate-address --network-interface-id "${ENI_ID}" --allocation-id "${ELASTICIP_ID}"
RV=$?

if [[ ${RV} != 0 ]]; then
    log "ERROR: Unable to associate elastic IP ${ELASTICIP_ID} to instance ${INSTANCE_ID} (${ENI_ID})"
    exit ${RV}
else
    # We assume that if return value is not 0 then we have successfully associated an EIP
    log "SUCCESS: Associated ${ELASTICIP_ID} to instance ${INSTANCE_ID} (${ENI_ID})"
fi
