[template]
src = "squid_allow_regex_domains.tmpl"
dest = "/etc/squid3/allow_regex_domains.txt"
prefix = "/%%PROJECT%%/%%ARENA%%"

keys = [
    "/config/AllowRegexDomains",
]

reload_cmd = "service squid3 reload"
